language: node_js
node_js:
  - 'node'

notifications:
  email: false
before_script:
  - npm install -g yarn webpack
  - git checkout master
  - cd webextension
  - yarn
  - cd ..
  - yarn

install:
  - npm i --force
  - webpack --config=build/webpack.config.js && webpack --config=build/webpack.gf.config.js  && node build/userscript.js

script:
  - yarn build
  - cd webextension
  - yarn build
  - cd ..

after_success:
  - pwd
  - git commit -a -m "Travis build"
  - git status
  - git push "https://${GH_TOKEN}@${GH_REF}" master:master

cache:
  yarn: true
  webpack: true
  directories:
    - "node_modules"
    - "crx/node_modules"

env:
 global:
   - GH_REF: github.com/magicoflolis/Userscript-Plus.git